#Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d4jnd03e5dus73en8t2g-a.singapore-postgres.render.com:5432/moneymanger2
spring.datasource.username=moneymanger2_user
spring.datasource.password=SylXBv8JZQrARc1uxLcs5tf6HIl75msv