#Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d57ndt8gjchc739mrg20-a:5432/moneymanager_db_tvtt
spring.datasource.username=moneymanager_db_tvtt_user
spring.datasource.password=NUjuWiJAbT33tItB2KCkFHwT7zyeSwOk